# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2c455557647b5e94f4b6da3008cfde10a317436b31838d4514d7170b551b7e75a34b9e7251824f56203783c931f1a675d08e4e04b0673aaffef91e3bd9df761

test:
  secret_key_base: 1322afd1ae9d1eb5784430e32dfc55c648692207bbe44c95cfc7c63e89f13f1aa5b49547302716a7953eb7307c399fb56c0d81095a7444e3f231a169fdee7240

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
